# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/carlosrdrz/dev/bure/client

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/carlosrdrz/dev/bure/client

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/carlosrdrz/dev/bure/client/CMakeFiles /home/carlosrdrz/dev/bure/client/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/carlosrdrz/dev/bure/client/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named client

# Build rule for target.
client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 client
.PHONY : client

# fast build rule for target.
client/fast:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/build
.PHONY : client/fast

#=============================================================================
# Target rules for targets named bure-ui

# Build rule for target.
bure-ui: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bure-ui
.PHONY : bure-ui

# fast build rule for target.
bure-ui/fast:
	$(MAKE) -f CMakeFiles/bure-ui.dir/build.make CMakeFiles/bure-ui.dir/build
.PHONY : bure-ui/fast

#=============================================================================
# Target rules for targets named bure-engine

# Build rule for target.
bure-engine: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bure-engine
.PHONY : bure-engine

# fast build rule for target.
bure-engine/fast:
	$(MAKE) -f CMakeFiles/bure-engine.dir/build.make CMakeFiles/bure-engine.dir/build
.PHONY : bure-engine/fast

engine/engine.o: engine/engine.cpp.o

.PHONY : engine/engine.o

# target to build an object file
engine/engine.cpp.o:
	$(MAKE) -f CMakeFiles/bure-engine.dir/build.make CMakeFiles/bure-engine.dir/engine/engine.cpp.o
.PHONY : engine/engine.cpp.o

engine/engine.i: engine/engine.cpp.i

.PHONY : engine/engine.i

# target to preprocess a source file
engine/engine.cpp.i:
	$(MAKE) -f CMakeFiles/bure-engine.dir/build.make CMakeFiles/bure-engine.dir/engine/engine.cpp.i
.PHONY : engine/engine.cpp.i

engine/engine.s: engine/engine.cpp.s

.PHONY : engine/engine.s

# target to generate assembly for a file
engine/engine.cpp.s:
	$(MAKE) -f CMakeFiles/bure-engine.dir/build.make CMakeFiles/bure-engine.dir/engine/engine.cpp.s
.PHONY : engine/engine.cpp.s

engine/entity.o: engine/entity.cpp.o

.PHONY : engine/entity.o

# target to build an object file
engine/entity.cpp.o:
	$(MAKE) -f CMakeFiles/bure-engine.dir/build.make CMakeFiles/bure-engine.dir/engine/entity.cpp.o
.PHONY : engine/entity.cpp.o

engine/entity.i: engine/entity.cpp.i

.PHONY : engine/entity.i

# target to preprocess a source file
engine/entity.cpp.i:
	$(MAKE) -f CMakeFiles/bure-engine.dir/build.make CMakeFiles/bure-engine.dir/engine/entity.cpp.i
.PHONY : engine/entity.cpp.i

engine/entity.s: engine/entity.cpp.s

.PHONY : engine/entity.s

# target to generate assembly for a file
engine/entity.cpp.s:
	$(MAKE) -f CMakeFiles/bure-engine.dir/build.make CMakeFiles/bure-engine.dir/engine/entity.cpp.s
.PHONY : engine/entity.cpp.s

engine/event_manager.o: engine/event_manager.cpp.o

.PHONY : engine/event_manager.o

# target to build an object file
engine/event_manager.cpp.o:
	$(MAKE) -f CMakeFiles/bure-engine.dir/build.make CMakeFiles/bure-engine.dir/engine/event_manager.cpp.o
.PHONY : engine/event_manager.cpp.o

engine/event_manager.i: engine/event_manager.cpp.i

.PHONY : engine/event_manager.i

# target to preprocess a source file
engine/event_manager.cpp.i:
	$(MAKE) -f CMakeFiles/bure-engine.dir/build.make CMakeFiles/bure-engine.dir/engine/event_manager.cpp.i
.PHONY : engine/event_manager.cpp.i

engine/event_manager.s: engine/event_manager.cpp.s

.PHONY : engine/event_manager.s

# target to generate assembly for a file
engine/event_manager.cpp.s:
	$(MAKE) -f CMakeFiles/bure-engine.dir/build.make CMakeFiles/bure-engine.dir/engine/event_manager.cpp.s
.PHONY : engine/event_manager.cpp.s

engine/game_map.o: engine/game_map.cpp.o

.PHONY : engine/game_map.o

# target to build an object file
engine/game_map.cpp.o:
	$(MAKE) -f CMakeFiles/bure-engine.dir/build.make CMakeFiles/bure-engine.dir/engine/game_map.cpp.o
.PHONY : engine/game_map.cpp.o

engine/game_map.i: engine/game_map.cpp.i

.PHONY : engine/game_map.i

# target to preprocess a source file
engine/game_map.cpp.i:
	$(MAKE) -f CMakeFiles/bure-engine.dir/build.make CMakeFiles/bure-engine.dir/engine/game_map.cpp.i
.PHONY : engine/game_map.cpp.i

engine/game_map.s: engine/game_map.cpp.s

.PHONY : engine/game_map.s

# target to generate assembly for a file
engine/game_map.cpp.s:
	$(MAKE) -f CMakeFiles/bure-engine.dir/build.make CMakeFiles/bure-engine.dir/engine/game_map.cpp.s
.PHONY : engine/game_map.cpp.s

engine/graphics.o: engine/graphics.cpp.o

.PHONY : engine/graphics.o

# target to build an object file
engine/graphics.cpp.o:
	$(MAKE) -f CMakeFiles/bure-engine.dir/build.make CMakeFiles/bure-engine.dir/engine/graphics.cpp.o
.PHONY : engine/graphics.cpp.o

engine/graphics.i: engine/graphics.cpp.i

.PHONY : engine/graphics.i

# target to preprocess a source file
engine/graphics.cpp.i:
	$(MAKE) -f CMakeFiles/bure-engine.dir/build.make CMakeFiles/bure-engine.dir/engine/graphics.cpp.i
.PHONY : engine/graphics.cpp.i

engine/graphics.s: engine/graphics.cpp.s

.PHONY : engine/graphics.s

# target to generate assembly for a file
engine/graphics.cpp.s:
	$(MAKE) -f CMakeFiles/bure-engine.dir/build.make CMakeFiles/bure-engine.dir/engine/graphics.cpp.s
.PHONY : engine/graphics.cpp.s

engine/system.o: engine/system.cpp.o

.PHONY : engine/system.o

# target to build an object file
engine/system.cpp.o:
	$(MAKE) -f CMakeFiles/bure-engine.dir/build.make CMakeFiles/bure-engine.dir/engine/system.cpp.o
.PHONY : engine/system.cpp.o

engine/system.i: engine/system.cpp.i

.PHONY : engine/system.i

# target to preprocess a source file
engine/system.cpp.i:
	$(MAKE) -f CMakeFiles/bure-engine.dir/build.make CMakeFiles/bure-engine.dir/engine/system.cpp.i
.PHONY : engine/system.cpp.i

engine/system.s: engine/system.cpp.s

.PHONY : engine/system.s

# target to generate assembly for a file
engine/system.cpp.s:
	$(MAKE) -f CMakeFiles/bure-engine.dir/build.make CMakeFiles/bure-engine.dir/engine/system.cpp.s
.PHONY : engine/system.cpp.s

engine/ui/container.o: engine/ui/container.cpp.o

.PHONY : engine/ui/container.o

# target to build an object file
engine/ui/container.cpp.o:
	$(MAKE) -f CMakeFiles/bure-ui.dir/build.make CMakeFiles/bure-ui.dir/engine/ui/container.cpp.o
.PHONY : engine/ui/container.cpp.o

engine/ui/container.i: engine/ui/container.cpp.i

.PHONY : engine/ui/container.i

# target to preprocess a source file
engine/ui/container.cpp.i:
	$(MAKE) -f CMakeFiles/bure-ui.dir/build.make CMakeFiles/bure-ui.dir/engine/ui/container.cpp.i
.PHONY : engine/ui/container.cpp.i

engine/ui/container.s: engine/ui/container.cpp.s

.PHONY : engine/ui/container.s

# target to generate assembly for a file
engine/ui/container.cpp.s:
	$(MAKE) -f CMakeFiles/bure-ui.dir/build.make CMakeFiles/bure-ui.dir/engine/ui/container.cpp.s
.PHONY : engine/ui/container.cpp.s

engine/ui/input_box.o: engine/ui/input_box.cpp.o

.PHONY : engine/ui/input_box.o

# target to build an object file
engine/ui/input_box.cpp.o:
	$(MAKE) -f CMakeFiles/bure-ui.dir/build.make CMakeFiles/bure-ui.dir/engine/ui/input_box.cpp.o
.PHONY : engine/ui/input_box.cpp.o

engine/ui/input_box.i: engine/ui/input_box.cpp.i

.PHONY : engine/ui/input_box.i

# target to preprocess a source file
engine/ui/input_box.cpp.i:
	$(MAKE) -f CMakeFiles/bure-ui.dir/build.make CMakeFiles/bure-ui.dir/engine/ui/input_box.cpp.i
.PHONY : engine/ui/input_box.cpp.i

engine/ui/input_box.s: engine/ui/input_box.cpp.s

.PHONY : engine/ui/input_box.s

# target to generate assembly for a file
engine/ui/input_box.cpp.s:
	$(MAKE) -f CMakeFiles/bure-ui.dir/build.make CMakeFiles/bure-ui.dir/engine/ui/input_box.cpp.s
.PHONY : engine/ui/input_box.cpp.s

engine/ui/label.o: engine/ui/label.cpp.o

.PHONY : engine/ui/label.o

# target to build an object file
engine/ui/label.cpp.o:
	$(MAKE) -f CMakeFiles/bure-ui.dir/build.make CMakeFiles/bure-ui.dir/engine/ui/label.cpp.o
.PHONY : engine/ui/label.cpp.o

engine/ui/label.i: engine/ui/label.cpp.i

.PHONY : engine/ui/label.i

# target to preprocess a source file
engine/ui/label.cpp.i:
	$(MAKE) -f CMakeFiles/bure-ui.dir/build.make CMakeFiles/bure-ui.dir/engine/ui/label.cpp.i
.PHONY : engine/ui/label.cpp.i

engine/ui/label.s: engine/ui/label.cpp.s

.PHONY : engine/ui/label.s

# target to generate assembly for a file
engine/ui/label.cpp.s:
	$(MAKE) -f CMakeFiles/bure-ui.dir/build.make CMakeFiles/bure-ui.dir/engine/ui/label.cpp.s
.PHONY : engine/ui/label.cpp.s

engine/ui/selector.o: engine/ui/selector.cpp.o

.PHONY : engine/ui/selector.o

# target to build an object file
engine/ui/selector.cpp.o:
	$(MAKE) -f CMakeFiles/bure-ui.dir/build.make CMakeFiles/bure-ui.dir/engine/ui/selector.cpp.o
.PHONY : engine/ui/selector.cpp.o

engine/ui/selector.i: engine/ui/selector.cpp.i

.PHONY : engine/ui/selector.i

# target to preprocess a source file
engine/ui/selector.cpp.i:
	$(MAKE) -f CMakeFiles/bure-ui.dir/build.make CMakeFiles/bure-ui.dir/engine/ui/selector.cpp.i
.PHONY : engine/ui/selector.cpp.i

engine/ui/selector.s: engine/ui/selector.cpp.s

.PHONY : engine/ui/selector.s

# target to generate assembly for a file
engine/ui/selector.cpp.s:
	$(MAKE) -f CMakeFiles/bure-ui.dir/build.make CMakeFiles/bure-ui.dir/engine/ui/selector.cpp.s
.PHONY : engine/ui/selector.cpp.s

engine/ui_manager.o: engine/ui_manager.cpp.o

.PHONY : engine/ui_manager.o

# target to build an object file
engine/ui_manager.cpp.o:
	$(MAKE) -f CMakeFiles/bure-engine.dir/build.make CMakeFiles/bure-engine.dir/engine/ui_manager.cpp.o
.PHONY : engine/ui_manager.cpp.o

engine/ui_manager.i: engine/ui_manager.cpp.i

.PHONY : engine/ui_manager.i

# target to preprocess a source file
engine/ui_manager.cpp.i:
	$(MAKE) -f CMakeFiles/bure-engine.dir/build.make CMakeFiles/bure-engine.dir/engine/ui_manager.cpp.i
.PHONY : engine/ui_manager.cpp.i

engine/ui_manager.s: engine/ui_manager.cpp.s

.PHONY : engine/ui_manager.s

# target to generate assembly for a file
engine/ui_manager.cpp.s:
	$(MAKE) -f CMakeFiles/bure-engine.dir/build.make CMakeFiles/bure-engine.dir/engine/ui_manager.cpp.s
.PHONY : engine/ui_manager.cpp.s

engine/utils/config.o: engine/utils/config.cpp.o

.PHONY : engine/utils/config.o

# target to build an object file
engine/utils/config.cpp.o:
	$(MAKE) -f CMakeFiles/bure-engine.dir/build.make CMakeFiles/bure-engine.dir/engine/utils/config.cpp.o
.PHONY : engine/utils/config.cpp.o

engine/utils/config.i: engine/utils/config.cpp.i

.PHONY : engine/utils/config.i

# target to preprocess a source file
engine/utils/config.cpp.i:
	$(MAKE) -f CMakeFiles/bure-engine.dir/build.make CMakeFiles/bure-engine.dir/engine/utils/config.cpp.i
.PHONY : engine/utils/config.cpp.i

engine/utils/config.s: engine/utils/config.cpp.s

.PHONY : engine/utils/config.s

# target to generate assembly for a file
engine/utils/config.cpp.s:
	$(MAKE) -f CMakeFiles/bure-engine.dir/build.make CMakeFiles/bure-engine.dir/engine/utils/config.cpp.s
.PHONY : engine/utils/config.cpp.s

engine/utils/error.o: engine/utils/error.cpp.o

.PHONY : engine/utils/error.o

# target to build an object file
engine/utils/error.cpp.o:
	$(MAKE) -f CMakeFiles/bure-engine.dir/build.make CMakeFiles/bure-engine.dir/engine/utils/error.cpp.o
.PHONY : engine/utils/error.cpp.o

engine/utils/error.i: engine/utils/error.cpp.i

.PHONY : engine/utils/error.i

# target to preprocess a source file
engine/utils/error.cpp.i:
	$(MAKE) -f CMakeFiles/bure-engine.dir/build.make CMakeFiles/bure-engine.dir/engine/utils/error.cpp.i
.PHONY : engine/utils/error.cpp.i

engine/utils/error.s: engine/utils/error.cpp.s

.PHONY : engine/utils/error.s

# target to generate assembly for a file
engine/utils/error.cpp.s:
	$(MAKE) -f CMakeFiles/bure-engine.dir/build.make CMakeFiles/bure-engine.dir/engine/utils/error.cpp.s
.PHONY : engine/utils/error.cpp.s

game.o: game.cpp.o

.PHONY : game.o

# target to build an object file
game.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/game.cpp.o
.PHONY : game.cpp.o

game.i: game.cpp.i

.PHONY : game.i

# target to preprocess a source file
game.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/game.cpp.i
.PHONY : game.cpp.i

game.s: game.cpp.s

.PHONY : game.s

# target to generate assembly for a file
game.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/game.cpp.s
.PHONY : game.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/main.cpp.s
.PHONY : main.cpp.s

player.o: player.cpp.o

.PHONY : player.o

# target to build an object file
player.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/player.cpp.o
.PHONY : player.cpp.o

player.i: player.cpp.i

.PHONY : player.i

# target to preprocess a source file
player.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/player.cpp.i
.PHONY : player.cpp.i

player.s: player.cpp.s

.PHONY : player.s

# target to generate assembly for a file
player.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/player.cpp.s
.PHONY : player.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... client"
	@echo "... rebuild_cache"
	@echo "... bure-ui"
	@echo "... test"
	@echo "... bure-engine"
	@echo "... engine/engine.o"
	@echo "... engine/engine.i"
	@echo "... engine/engine.s"
	@echo "... engine/entity.o"
	@echo "... engine/entity.i"
	@echo "... engine/entity.s"
	@echo "... engine/event_manager.o"
	@echo "... engine/event_manager.i"
	@echo "... engine/event_manager.s"
	@echo "... engine/game_map.o"
	@echo "... engine/game_map.i"
	@echo "... engine/game_map.s"
	@echo "... engine/graphics.o"
	@echo "... engine/graphics.i"
	@echo "... engine/graphics.s"
	@echo "... engine/system.o"
	@echo "... engine/system.i"
	@echo "... engine/system.s"
	@echo "... engine/ui/container.o"
	@echo "... engine/ui/container.i"
	@echo "... engine/ui/container.s"
	@echo "... engine/ui/input_box.o"
	@echo "... engine/ui/input_box.i"
	@echo "... engine/ui/input_box.s"
	@echo "... engine/ui/label.o"
	@echo "... engine/ui/label.i"
	@echo "... engine/ui/label.s"
	@echo "... engine/ui/selector.o"
	@echo "... engine/ui/selector.i"
	@echo "... engine/ui/selector.s"
	@echo "... engine/ui_manager.o"
	@echo "... engine/ui_manager.i"
	@echo "... engine/ui_manager.s"
	@echo "... engine/utils/config.o"
	@echo "... engine/utils/config.i"
	@echo "... engine/utils/config.s"
	@echo "... engine/utils/error.o"
	@echo "... engine/utils/error.i"
	@echo "... engine/utils/error.s"
	@echo "... game.o"
	@echo "... game.i"
	@echo "... game.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... player.o"
	@echo "... player.i"
	@echo "... player.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

